import numpy as np
fdata = np.random.normal(loc=0,scale=1,size=1000)
print(fdata)
minimum = np.min(fdata)
maximum = np.max(fdata)
mean = np.mean(fdata)
median = np.median(fdata)
variance = np.var(fdata)
std_dev = np.std(fdata)

print(f"{'MINIMUM: ':20s}{minimum:>9.4f}")
print(f"{'MAXIMUM: ':20s}{maximum:>9.4f}")
print(f"{'MEAN: ':20s}{mean:>9.4f}")
print(f"{'MEDIAN: ':20s}{median:>9.4f}")
print(f"{'VARIANCE: ':20s}{variance:>9.4f}")
print(f"{'STANDARD DEVIATION: ':20s}{std_dev:>9.4f}")
print('')

idata = np.random.randint(0,101,1000)
print(idata)
minimum = np.min(idata)
maximum = np.max(idata)
mean = np.mean(idata)
median = np.median(idata)
variance = np.var(idata)
std_dev = np.std(idata)

print(f"{'MINIMUM: ':20s}{minimum:>9d}")
print(f"{'MAXIMUM: ':20s}{maximum:>9d}")
print(f"{'MEAN: ':20s}{mean:>9.4f}")
print(f"{'MEDIAN: ':20s}{median:>9.4f}")
print(f"{'VARIANCE: ':20s}{variance:>9.4f}")
print(f"{'STANDARD DEVIATION: ':20s}{std_dev:>9.4f}")
